# server 
organ: Avatar
httpPort: 8080
serverMode: debug   ## debug:开发环境,release:生产环境
jwtSecret: 3225180e91b99ff350fcc2a968d2f76
xxteaKey: d9bfc5e41ca55dce527a3476636bd7e4

# mysql database 
mysqlHost: 172.16.1.101
mysqlPort: 3306
mysqlUser: root
mysqlPassword: root
mysqlDbName: avatar

# redis database 
redisUrl: 172.16.1.101:6379
redisPassword: redis
redisPoolSize: 20
redisPoolMinIdel: 5

# logger 
loggerMaxSize: 500      ## single log file size, unit MB
loggerMaxAge: 10        ## maximum number of days to retain
loggerMaxBackups: 200   ## maximum number of old log files to retain

gormLoggerFileName: /usr/local/avatar/logs/server-go/gorm.log
paramsLoggerFileName: /usr/local/avatar/logs/server-go/params.log
monitorLoggerFileName: /usr/local/avatar/logs/server-go/monitor.log