# server 
organ: Avatar
httpPort: 8000
serverMode: debug   ## debug:development environment,release:production environment
jwtSecret: 3225180e91b99ff350fcc2a968d2f76
xxteaKey: d9bfc5e41ca55dce527a3476636bd7e4

# mysql database 
mysqlHost: 127.0.0.1
mysqlPort: 3306
mysqlUser: root
mysqlPassword: root
mysqlDbName: avatar

# redis database 
redisUrl: 127.0.0.1:6379
redisPassword: redis
redisPoolSize: 20
redisPoolMinIdel: 5

# logger 
loggerMaxSize: 500      ## single log file size, unit MB
loggerMaxAge: 10        ## maximum number of days to retain
loggerMaxBackups: 200   ## maximum number of old log files to retain

gormLoggerFileName: logs/gorm.log
paramsLoggerFileName: logs/params.log
monitorLoggerFileName: logs/monitor.log